### ISSUE TITLE
FILE SHREDDER

### ISSUE THREAD

**Issue by MD189756** [ADBeveridge/raider#155]
FILE SHREDDER is slow compared to Windows programs that shred quickly. And the program also does not allow dragging files into the program in order to shred the files. This is the only file shredding program we have on Linux. Fix the option to drag files. Any type of file into the program in order to shred. And make the program shred quickly. Because the software's shredding is very slow on all Linux I've tried, especially in Kubuntu.

**Comment by ADBeveridge** [comment]
Will look into this next week after finals. The reason why it is so slow - I have the program obfuscating the file 3.3 times more than the default of `shred`, the command line program's default. I can change that to a more reasonable value. Regarding dragging files - i have fully set up file drag and drop, so I think the issue is you using KDE - KDE and GNOME (the toolkit used to develop my program) use very different DND protocols. But I will look into this further; perhaps there is a setting I can change that allows KDE DND too.

**Comment by ADBeveridge** [comment]
I halved the shredding time by using a more sensible default time. I'll close this for now, but if you have any nitpicks, feel free to reopen this or create a new issue. Happy Holidays!
