### ISSUE TITLE
Won't start

### ISSUE THREAD

**Issue by tio-trom** [ADBeveridge/raider#41]
I am using Arch + XFCE and the latest Shredder flatpak. I get this error:

```
libEGL warning: MESA-LOADER: failed to retrieve device information

libEGL warning: DRI2: could not open /dev/dri/card0 (No such file or directory)
libGL error: MESA-LOADER: failed to retrieve device information

(raider:2): Gtk-WARNING **: 03:42:53.861: Theme parser error: gtk.css:4403:12-17: "shade" is not a valid color name.

(raider:2): Gtk-WARNING **: 03:42:53.861: Theme parser error: gtk.css:4420:12-15: "mix" is not a valid color name.

(raider:2): Gtk-WARNING **: 03:42:53.861: Theme parser error: gtk.css:4425:12-15: "mix" is not a valid color name.
No provider of glGetShaderiv found.  Requires one of:
    Desktop OpenGL 2.0
    OpenGL ES 2.0

```

**Comment by ADBeveridge** [comment]
I updated Raider to GTK4 which requires a OpenGL version higher than 2.0 (I am running OpenGL 4.1). I had this problem when I was using my older computer (from 2005), and fixed it by running it on a newer computer. To fix this I can give you a flatpak bundle to the older version which uses GTK3.
Here is the zip: [com.github.ADBeveridge.Raider.zip](https://github.com/ADBeveridge/raider/files/9162878/com.github.ADBeveridge.Raider.zip)
It contains the flatpak. To install just right click and click on Software Install. (Remove the newer version of Raider, though, it'll get confused.)

It sucks though...I couldn't update my app to GTK4 for a while because I didn't have access to a newer computer.

**Comment by lomapur** [comment]
Sorry to comment on closed issue, but I just ran into the same issue after freshly installing from Flathub - it looks like device=dri access permission may be missing in Flatpak (or at least it was missing when I reinstalled it yesterday)?

Turning the permission on in Flatseal has resolved the issue.

**Comment by tio-trom** [comment]
> Sorry to comment on closed issue, but I just ran into the same issue after freshly installing from Flathub - it looks like device=dri access permission may be missing in Flatpak (or at least it was missing when I reinstalled it yesterday)?
> 
> Turning the permission on in Flatseal has resolved the issue.

I confirm this is the case for me too.

**Comment by ADBeveridge** [comment]
Ok, I fix this right now...thanks guys for the help!

**Comment by ADBeveridge** [comment]
Just tested it, now I finally can click outside popovers and they close (they wouldn't without the dri thing.)
