### ISSUE TITLE
Toast is Slow

### ISSUE THREAD

**Issue by caribo** [ADBeveridge/raider#55]
The use of toast to signal completion of a single file being shred introduces significant delays when processing many smaller files located on tmpfs filesystem. Shredding many small files using "shred -zuv" is very quick to complete. Shredding the same number of small files in raider takes considerably longer due to the delays introduced by toasting the shredding of each individual file. A rough estimation is that the toast takes a number of seconds per file, whereas the native shred command takes 1 second to complete. 

In my case the process would be optimised if the toast was only used to signal the end of all shredding.

**Comment by ADBeveridge** [comment]
I agree: I had some doubts about notifying for each file because only one toast is shown at a time. I'll probably use a threshold number, say 3 or 4 seconds, and all the files that get shredded within that will not have their own toasts, just one master one. And jobs that are completed within a half-second of each other will share a toast. Files that go for more than 4 seconds will get their own toast (unless there is a file that gets finished with it). Btw, have you noticed that a desktop notification in shown when Raider is in the background? I'll probably use the same rules for that too.

**Comment by caribo** [comment]
The revised approach to toasts is improved and should help with  the issue I have when shredding many smaller files. In addition to this you could also consider making notifications (toasts and background notifications) an on/off option in preferences. I am quite happy to see files being removed from the list once shredded and don't get much value form toasts or notifications at all.

**Comment by ADBeveridge** [comment]
I'll put the option in the preferences, will take a little time. I'll probably release in a week or a month, just depends on how involved it gets. But I'll definitely be working on it.

**Comment by ADBeveridge** [comment]
So, i instead did a good default (one notification at the end of a successful shredding session.
